# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdate',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme.Training'),
        ),
    ]
