# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_auto_20170717_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdate',
            name='pdf',
        ),
        migrations.AddField(
            model_name='training',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
