# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_auto_20170717_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdate',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_date', to='programme.Training'),
        ),
    ]
