# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_auto_20170718_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='programme.ProgramCategory'),
        ),
        migrations.AlterField(
            model_name='training',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training', to='programme.Program'),
        ),
        migrations.AlterField(
            model_name='trainingdate',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_date', to='programme.Training'),
        ),
    ]
