# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_auto_20170719_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdate',
            name='end_date',
            field=models.DateField(help_text='Format : YYYY-DD-MM'),
        ),
        migrations.AlterField(
            model_name='trainingdate',
            name='start_date',
            field=models.DateField(help_text='Format : YYYY-DD-MM'),
        ),
    ]
